# Generated by Django 5.0.7 on 2024-08-05 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Coupon_Codes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Codes', models.CharField(max_length=100)),
                ('Discount', models.IntegerField(blank=True)),
                ('Max_Amount_Discount', models.IntegerField(blank=True, null=True)),
                ('Amount', models.IntegerField(blank=True)),
            ],
        ),
    ]
