# Generated by Django 5.0.7 on 2024-08-05 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Checkout', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coupon_codes',
            name='Amount',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='coupon_codes',
            name='Discount',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
