# Generated by Django 5.0.7 on 2024-08-05 15:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Checkout', '0002_alter_coupon_codes_amount_and_more'),
        ('accounts', '0002_registered_users_refresh_token'),
    ]

    operations = [
        migrations.CreateModel(
            name='User_Addresses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=20)),
                ('building', models.CharField(max_length=255)),
                ('area', models.CharField(max_length=255)),
                ('landmark', models.CharField(blank=True, max_length=255, null=True)),
                ('pincode', models.CharField(max_length=10)),
                ('town', models.CharField(max_length=255)),
                ('state', models.CharField(max_length=255)),
                ('Email', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='addresses', to='accounts.registered_users', to_field='Email')),
            ],
        ),
    ]
