# Generated by Django 5.0.7 on 2024-08-01 11:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0002_registered_users_refresh_token'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart_Items',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ProductID', models.CharField(max_length=200)),
                ('Quantity', models.IntegerField()),
                ('Email', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cart_items', to='accounts.registered_users', to_field='Email')),
            ],
        ),
    ]
